ÿØÿà JFIF  H H  ÿá	©Exif  MM *                  b       j(       1       r2       †‡i       œ   È   H      H   Adobe Photoshop 7.0 2009:08:19 16:37:22                           2                          (             &      {       H      H   ÿØÿà JFIF  H H  ÿí Adobe_CM ÿî Adobe d€   ÿÛ „ 			
ÿÀ   €" ÿÝ  ÿÄ?          	
         	
 3 !1AQa"q2‘¡±B#$RÁb34r‚ÑC%’Sðáñcs5¢²ƒ&D“TdEÂ£t6ÒUâeò³„ÃÓuãóF'”¤…´•ÄÔäô¥µÅÕåõVfv†–¦¶ÆÖæö7GWgw‡—§·Ç×ç÷ 5 !1AQaq"2‘¡±B#ÁRÑð3$bár‚’CScs4ñ%¢²ƒ&5ÂÒD“T£dEU6teâò³„ÃÓuãóF”¤…´•ÄÔäô¥µÅÕåõVfv†–¦¶ÆÖæö'7GWgw‡—§·ÇÿÚ   ? îz·ÖVáÜì\J]“{m†Ç8Mu—5®õ-ú6,|_¬jŒ‹s]”Òí¯¡Ì,Øóôk­ÌcS½¿ÍYê+6Ú[ÕòÃ¯m4³6› ¼	#ì¶»ªwÒcëÙmÿ ‚~-è8¹­vCö†·«iý+žXç¹ÆÆ»íX›¿ÓfN-Îý%e»ôžõVR‘—ÏÃ© <²œŒ¾j¢h®âdtÛzƒ[`n;K®§lØo©µ­Û7°î­íýþ°±˜ÕÝögØûŽÔú¬ý :û½V[èûw7Ù¿Ôõ†ïK¥fÉ³u5Ò×Œr`s1±ÚöWôÙê5ÍÚØÔä2‡4Ycòí¶·åS}FKÙé^Çzu¶MØØþnŸWÔ«ý7éœr1ë_÷\+øæb5Ö»[…Òý·Ž`±{]}T1Â›«fEv{ÐÛnÔ:zûµÙïÆ­×»ÙcëÚÛÛ]nâÛµŽ£Óþ^õH·s2qñî4×‘XmÆ²·½¢¼LÆnÝe”ØÇ3fÛ}?Ðúž’³^&F[ê`pû&]ÙØÂãk´¿}ÛGé¬u)	HÂDäHø$¯ëVäÓ]$›Ú×‡+hÚ÷ÛT°>Àë¿˜uŸ¡ßìBoÖŒoFËhmmežÒÇ’ÇØÜðOvËXçnô,ý/î(5˜Ø€æÐo–\ÃSMg{q-¹ÞŸéí¾³ì³g¦êýˆ½2Še,¼×Y©Ž-ÿ ek:£.{ÐïZ¿uÿ …~ÏKýFSýáü¾TqÎ¾aü¾Wi½B—ãäd0×&ZA¿uniÛîkÕ*~±2úšjÅ±÷Xæ²ªZêÎíì~F¶¶ÏJ½µÓo¨ËêÛ•¡²Ìmý3‘Nu—{cAs™MíÇÝô¿Icý:›ûˆ#ø¾5ÛIéÎ«ªs7;§ïÉv×WNêÜë-õëþúoðH™žõÝ&gOPÿ ±Ó§«×‘E—cSe»1ëÉc<Yêí©­Ÿç¿@æ Ù×Ûµ–câÙ‘M×(µ®cCß¥ž«Ùú7;Ô¯üªÓVUäavSŒS,©Ìu`Ü)ý+Ûo©ïßê>»Yêzˆø´ã=Øý0²ÚßÓž.àtn”½Ïý%Wú¶lúÌÝþ….)¯òÙ\R4.—äÉÿ X©e™u.Ù¼<µõ—’ÒÚö·Yëþ’×¶¶=ìôÿ °¥w^¯¹Ì¡øö
î³Ó{˜$ÓéŸN·ïÙk¯õ¿Céÿ -Î‹E¾§Ýi§%Î{ê€<ú›Ù`¯×nË½Ÿ¦OgE¢Ö‘}×\÷Uu.±îíÈôÅ… 0W^ÆÒÏKÒc+GõšêšÉ®¨ÿ oãzÎ£cÅ¬²†l0	žÛ[î÷2§]¶ïýV•=t^(u8—XËZË--ÚMm±î¦§9›÷YîªÇYèïôëSCÁ{ë±ÛÍ•\ÌŠß"C˜Ê¨Ùôš±˜õúŒJ®‰E-©”ß}m©¬cƒ^öÖ÷]Smxnÿ kì³ù—Uê3ôv¥úËé_Ê•úÛé_ÊŸÿÐí:ý_V­È,Ì¸Qœ[­•9ÀG·×mm{>úoÌú¥}¡ßnÎoÙÙ;}[½ãûU~…¿½·Ô^(’§–¸õàßúßøçS-qëÁ¿õ¿ç¿LtñÑÿ e8tÒF»ýMß;Yõ¿ðE"ÞžCŸa°^øqßêzÞ›¸nïè›ý/ÌþoÒÿ ¾eIXGåØmòÿ ‚Î6Ë°Ûåÿ úO}_ôGÙôgù½ûwoýJ—ê9ÿ ³
Þq–»Ö›,Þ×oØ,Þ}}ž Ûüöÿ  ¾aI(ôùÁTz|ŸàþÇé7·£lÉ/už‰¨ý.Áînô´ÿ Kþ‹þÒÿ 
‰Hèßi¤Iö«7~ß´z?§çôÑþŸø/Sþ|Ð’CqòtGQòt~“ÀoE-Ãýž÷µ¢ŸÕözjÞÝÞ®öÿ ¦ú~¯é(oL;†+íi&¿Vc×³oæÿ ÜŸ_þ³êÚuóBIŸ.Ý<¿EQØ|›tÿ ¹~”`èŸc·iw¡±ž©>¤Ç«vÝÓúOSí_hõÂ¤WÙö¶Û¶~ÑéWêcfë½ä}?_ýv/—F=>_§øIO—üð¶~ªI|ª’{#õRKåT’SÿÙÿí@Photoshop 3.0 8BIM%                     8BIMí      H     H    8BIM&               ?€  8BIM        x8BIM        8BIMó     	         8BIM
       8BIM'     
        8BIMõ     H /ff  lff       /ff  ¡™š       2    Z         5    -        8BIMø     p  ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿè    ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿè    ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿè    ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿè  8BIM          @  @    8BIM         8BIM    Q              2      S P S U _ H O R I Z _ R G B                                   2                                            null      boundsObjc         Rct1       Top long        Leftlong        Btomlong   2    Rghtlong     slicesVlLs   Objc        slice      sliceIDlong       groupIDlong       originenum   ESliceOrigin   autoGenerated    Typeenum   
ESliceType    Img    boundsObjc         Rct1       Top long        Leftlong        Btomlong   2    Rghtlong     urlTEXT         nullTEXT         MsgeTEXT        altTagTEXT        cellTextIsHTMLbool   cellTextTEXT        	horzAlignenum   ESliceHorzAlign   default   	vertAlignenum   ESliceVertAlign   default   bgColorTypeenum   ESliceBGColorType    None   	topOutsetlong       
leftOutsetlong       bottomOutsetlong       rightOutsetlong     8BIM        8BIM    —      €     €  !   {  ÿØÿà JFIF  H H  ÿí Adobe_CM ÿî Adobe d€   ÿÛ „ 			
ÿÀ   €" ÿÝ  ÿÄ?          	
         	
 3 !1AQa"q2‘¡±B#$RÁb34r‚ÑC%’Sðáñcs5¢²ƒ&D“TdEÂ£t6ÒUâeò³„ÃÓuãóF'”¤…´•ÄÔäô¥µÅÕåõVfv†–¦¶ÆÖæö7GWgw‡—§·Ç×ç÷ 5 !1AQaq"2‘¡±B#ÁRÑð3$bár‚’CScs4ñ%¢²ƒ&5ÂÒD“T£dEU6teâò³„ÃÓuãóF”¤…´•ÄÔäô¥µÅÕåõVfv†–¦¶ÆÖæö'7GWgw‡—§·ÇÿÚ   ? îz·ÖVáÜì\J]“{m†Ç8Mu—5®õ-ú6,|_¬jŒ‹s]”Òí¯¡Ì,Øóôk­ÌcS½¿ÍYê+6Ú[ÕòÃ¯m4³6› ¼	#ì¶»ªwÒcëÙmÿ ‚~-è8¹­vCö†·«iý+žXç¹ÆÆ»íX›¿ÓfN-Îý%e»ôžõVR‘—ÏÃ© <²œŒ¾j¢h®âdtÛzƒ[`n;K®§lØo©µ­Û7°î­íýþ°±˜ÕÝögØûŽÔú¬ý :û½V[èûw7Ù¿Ôõ†ïK¥fÉ³u5Ò×Œr`s1±ÚöWôÙê5ÍÚØÔä2‡4Ycòí¶·åS}FKÙé^Çzu¶MØØþnŸWÔ«ý7éœr1ë_÷\+øæb5Ö»[…Òý·Ž`±{]}T1Â›«fEv{ÐÛnÔ:zûµÙïÆ­×»ÙcëÚÛÛ]nâÛµŽ£Óþ^õH·s2qñî4×‘XmÆ²·½¢¼LÆnÝe”ØÇ3fÛ}?Ðúž’³^&F[ê`pû&]ÙØÂãk´¿}ÛGé¬u)	HÂDäHø$¯ëVäÓ]$›Ú×‡+hÚ÷ÛT°>Àë¿˜uŸ¡ßìBoÖŒoFËhmmežÒÇ’ÇØÜðOvËXçnô,ý/î(5˜Ø€æÐo–\ÃSMg{q-¹ÞŸéí¾³ì³g¦êýˆ½2Še,¼×Y©Ž-ÿ ek:£.{ÐïZ¿uÿ …~ÏKýFSýáü¾TqÎ¾aü¾Wi½B—ãäd0×&ZA¿uniÛîkÕ*~±2úšjÅ±÷Xæ²ªZêÎíì~F¶¶ÏJ½µÓo¨ËêÛ•¡²Ìmý3‘Nu—{cAs™MíÇÝô¿Icý:›ûˆ#ø¾5ÛIéÎ«ªs7;§ïÉv×WNêÜë-õëþúoðH™žõÝ&gOPÿ ±Ó§«×‘E—cSe»1ëÉc<Yêí©­Ÿç¿@æ Ù×Ûµ–câÙ‘M×(µ®cCß¥ž«Ùú7;Ô¯üªÓVUäavSŒS,©Ìu`Ü)ý+Ûo©ïßê>»Yêzˆø´ã=Øý0²ÚßÓž.àtn”½Ïý%Wú¶lúÌÝþ….)¯òÙ\R4.—äÉÿ X©e™u.Ù¼<µõ—’ÒÚö·Yëþ’×¶¶=ìôÿ °¥w^¯¹Ì¡øö
î³Ó{˜$ÓéŸN·ïÙk¯õ¿Céÿ -Î‹E¾§Ýi§%Î{ê€<ú›Ù`¯×nË½Ÿ¦OgE¢Ö‘}×\÷Uu.±îíÈôÅ… 0W^ÆÒÏKÒc+GõšêšÉ®¨ÿ oãzÎ£cÅ¬²†l0	žÛ[î÷2§]¶ïýV•=t^(u8—XËZË--ÚMm±î¦§9›÷YîªÇYèïôëSCÁ{ë±ÛÍ•\ÌŠß"C˜Ê¨Ùôš±˜õúŒJ®‰E-©”ß}m©¬cƒ^öÖ÷]Smxnÿ kì³ù—Uê3ôv¥úËé_Ê•úÛé_ÊŸÿÐí:ý_V­È,Ì¸Qœ[­•9ÀG·×mm{>úoÌú¥}¡ßnÎoÙÙ;}[½ãûU~…¿½·Ô^(’§–¸õàßúßøçS-qëÁ¿õ¿ç¿LtñÑÿ e8tÒF»ýMß;Yõ¿ðE"ÞžCŸa°^øqßêzÞ›¸nïè›ý/ÌþoÒÿ ¾eIXGåØmòÿ ‚Î6Ë°Ûåÿ úO}_ôGÙôgù½ûwoýJ—ê9ÿ ³
Þq–»Ö›,Þ×oØ,Þ}}ž Ûüöÿ  ¾aI(ôùÁTz|ŸàþÇé7·£lÉ/už‰¨ý.Áînô´ÿ Kþ‹þÒÿ 
‰Hèßi¤Iö«7~ß´z?§çôÑþŸø/Sþ|Ð’CqòtGQòt~“ÀoE-Ãýž÷µ¢ŸÕözjÞÝÞ®öÿ ¦ú~¯é(oL;†+íi&¿Vc×³oæÿ ÜŸ_þ³êÚuóBIŸ.Ý<¿EQØ|›tÿ ¹~”`èŸc·iw¡±ž©>¤Ç«vÝÓúOSí_hõÂ¤WÙö¶Û¶~ÑéWêcfë½ä}?_ýv/—F=>_§øIO—üð¶~ªI|ª’{#õRKåT’SÿÙ 8BIM!     U       A d o b e   P h o t o s h o p    A d o b e   P h o t o s h o p   7 . 0    8BIM          ÿáöhttp://ns.adobe.com/xap/1.0/ <?xpacket begin='ï»¿' id='W5M0MpCehiHzreSzNTczkc9d'?>
<?adobe-xap-filters esc="CR"?>
<x:xapmeta xmlns:x='adobe:ns:meta/' x:xaptk='XMP toolkit 2.8.2-33, framework 1.5'>
<rdf:RDF xmlns:rdf='http://www.w3.org/1999/02/22-rdf-syntax-ns#' xmlns:iX='http://ns.adobe.com/iX/1.0/'>

 <rdf:Description about='uuid:96faef7b-8cff-11de-81b9-8db8bf402dab'
  xmlns:exif='http://ns.adobe.com/exif/1.0/'>
  <exif:PixelXDimension>935</exif:PixelXDimension>
  <exif:PixelYDimension>164</exif:PixelYDimension>
  <exif:ColorSpace>1</exif:ColorSpace>
  <exif:NativeDigest>36864,40960,40961,37121,37122,40962,40963,37510,40964,36867,36868,33434,33437,34850,34852,34855,34856,37377,37378,37379,37380,37381,37382,37383,37384,37385,37386,37396,41483,41484,41486,41487,41488,41492,41493,41495,41728,41729,41730,41985,41986,41987,41988,41989,41990,41991,41992,41993,41994,41995,41996,42016,0,2,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,20,22,23,24,25,26,27,28,30;A11ADFBB355DC928916A4A01A0A78BFA</exif:NativeDigest>
 </rdf:Description>

 <rdf:Description about='uuid:96faef7b-8cff-11de-81b9-8db8bf402dab'
  xmlns:pdf='http://ns.adobe.com/pdf/1.3/'>
  <!-- pdf:Creator is aliased -->
  <!-- pdf:CreationDate is aliased -->
  <!-- pdf:ModDate is aliased -->
 </rdf:Description>

 <rdf:Description about='uuid:96faef7b-8cff-11de-81b9-8db8bf402dab'
  xmlns:photoshop='http://ns.adobe.com/photoshop/1.0/'>
  <photoshop:ColorMode>3</photoshop:ColorMode>
  <photoshop:ICCProfile>sRGB IEC61966-2.1</photoshop:ICCProfile>
  <photoshop:History></photoshop:History>
 </rdf:Description>

 <rdf:Description about='uuid:96faef7b-8cff-11de-81b9-8db8bf402dab'
  xmlns:tiff='http://ns.adobe.com/tiff/1.0/'>
  <tiff:Orientation>1</tiff:Orientation>
  <tiff:XResolution>3000000/10000</tiff:XResolution>
  <tiff:YResolution>3000000/10000</tiff:YResolution>
  <tiff:ResolutionUnit>2</tiff:ResolutionUnit>
  <tiff:NativeDigest>256,257,258,259,262,274,277,284,530,531,282,283,296,301,318,319,529,532,306,270,271,272,305,315,33432;B3689D555CD189F8C97AEE68BF9885D2</tiff:NativeDigest>
 </rdf:Description>

 <rdf:Description about='uuid:96faef7b-8cff-11de-81b9-8db8bf402dab'
  xmlns:xap='http://ns.adobe.com/xap/1.0/'>
  <xap:CreatorTool>Adobe Photoshop CS3 Macintosh</xap:CreatorTool>
  <xap:CreateDate>2008-04-06T22:38:28-04:00</xap:CreateDate>
  <xap:ModifyDate>2008-04-06T22:38:28-04:00</xap:ModifyDate>
  <xap:MetadataDate>2008-04-06T22:38:28-04:00</xap:MetadataDate>
  <!-- xap:Format is aliased -->
 </rdf:Description>

 <rdf:Description about='uuid:96faef7b-8cff-11de-81b9-8db8bf402dab'
  xmlns:stRef='http://ns.adobe.com/xap/1.0/sType/ResourceRef#'
  xmlns:xapMM='http://ns.adobe.com/xap/1.0/mm/'>
  <xapMM:DocumentID>adobe:docid:photoshop:96faef79-8cff-11de-81b9-8db8bf402dab</xapMM:DocumentID>
  <xapMM:InstanceID>uuid:F06E9262A105DD11944AA586326B6E16</xapMM:InstanceID>
  <xapMM:DerivedFrom rdf:parseType='Resource'>
   <stRef:instanceID>uuid:EE6E9262A105DD11944AA586326B6E16</stRef:instanceID>
   <stRef:documentID>uuid:EE6E9262A105DD11944AA586326B6E16</stRef:documentID>
  </xapMM:DerivedFrom>
 </rdf:Description>

 <rdf:Description about='uuid:96faef7b-8cff-11de-81b9-8db8bf402dab'
  xmlns:dc='http://purl.org/dc/elements/1.1/'>
  <dc:format>image/jpeg</dc:format>
 </rdf:Description>

</rdf:RDF>
</x:xapmeta>
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                       
<?xpacket end='w'?>ÿâXICC_PROFILE   HLino  mntrRGB XYZ Î  	  1  acspMSFT    IEC sRGB             öÖ     Ó-HP                                                 cprt  P   3desc  „   lwtpt  ð   bkpt     rXYZ     gXYZ  ,   bXYZ  @   dmnd  T   pdmdd  Ä   ˆvued  L   †view  Ô   $lumi  ø   meas     $tech  0   rTRC  <  gTRC  <  bTRC  <  text    Copyright (c) 1998 Hewlett-Packard Company  desc       sRGB IEC61966-2.1           sRGB IEC61966-2.1                                                  XYZ       óQ    ÌXYZ                 XYZ       o¢  8õ  XYZ       b™  ·…  ÚXYZ       $   „  ¶Ïdesc       IEC http://www.iec.ch           IEC http://www.iec.ch                                              desc       .IEC 61966-2.1 Default RGB colour space - sRGB           .IEC 61966-2.1 Default RGB colour space - sRGB                      desc       ,Reference Viewing Condition in IEC61966-2.1           ,Reference Viewing Condition in IEC61966-2.1                          view     ¤þ _. Ï íÌ  \ž   XYZ      L	V P   Wçmeas                            sig     CRT curv           
     # ( - 2 7 ; @ E J O T Y ^ c h m r w |  † ‹  • š Ÿ ¤ © ® ² · ¼ Á Æ Ë Ð Õ Û à å ë ð ö û%+28>ELRY`gnu|ƒ‹’š¡©±¹ÁÉÑÙáéòú&/8AKT]gqz„Ž˜¢¬¶ÁËÕàëõ !-8COZfr~Š–¢®ºÇÓàìù -;HUcq~Œš¨¶ÄÓáðþ+:IXgw†–¦µÅÕåö'7HYj{Œ¯ÀÑãõ+=Oat†™¬¿Òåø2FZn‚–ª¾Òçû		%	:	O	d	y		¤	º	Ï	å	û

'
=
T
j

˜
®
Å
Ü
ó"9Qi€˜°Èáù*C\uŽ§ÀÙó&@ZtŽ©ÃÞø.Id›¶Òî	%A^z–³Ïì	&Ca~›¹×õ1OmŒªÉè&Ed„£Ãã#Ccƒ¤Åå'Ij‹­Îð4Vx›½à&Il²ÖúAe‰®Ò÷@eŠ¯Õú Ek‘·Ý*QwžÅì;cŠ²Ú*R{£ÌõGp™Ãì@j”¾é>i”¿ê  A l ˜ Ä ð!!H!u!¡!Î!û"'"U"‚"¯"Ý#
#8#f#”#Â#ð$$M$|$«$Ú%	%8%h%—%Ç%÷&'&W&‡&·&è''I'z'«'Ü((?(q(¢(Ô))8)k))Ð**5*h*›*Ï++6+i++Ñ,,9,n,¢,×--A-v-«-á..L.‚.·.î/$/Z/‘/Ç/þ050l0¤0Û11J1‚1º1ò2*2c2›2Ô33F33¸3ñ4+4e4ž4Ø55M5‡5Â5ý676r6®6é7$7`7œ7×88P8Œ8È99B99¼9ù:6:t:²:ï;-;k;ª;è<'<e<¤<ã="=a=¡=à> >`> >à?!?a?¢?â@#@d@¦@çA)AjA¬AîB0BrBµB÷C:C}CÀDDGDŠDÎEEUEšEÞF"FgF«FðG5G{GÀHHKH‘H×IIcI©IðJ7J}JÄKKSKšKâL*LrLºMMJM“MÜN%NnN·O OIO“OÝP'PqP»QQPQ›QæR1R|RÇSS_SªSöTBTTÛU(UuUÂVV\V©V÷WDW’WàX/X}XËYYiY¸ZZVZ¦Zõ[E[•[å\5\†\Ö]']x]É^^l^½__a_³``W`ª`üaOa¢aõbIbœbðcCc—cëd@d”dée=e’eçf=f’fèg=g“géh?h–hìiCišiñjHjŸj÷kOk§kÿlWl¯mm`m¹nnknÄooxoÑp+p†pàq:q•qðrKr¦ss]s¸ttptÌu(u…uáv>v›vøwVw³xxnxÌy*y‰yçzFz¥{{c{Â|!||á}A}¡~~b~Â#„å€G€¨
kÍ‚0‚’‚ôƒWƒº„„€„ã…G…«††r†×‡;‡ŸˆˆiˆÎ‰3‰™‰þŠdŠÊ‹0‹–‹üŒcŒÊ1˜ÿŽfŽÎ6žnÖ‘?‘¨’’z’ã“M“¶” ”Š”ô•_•É–4–Ÿ—
—u—à˜L˜¸™$™™üšhšÕ›B›¯œœ‰œ÷dÒž@ž®ŸŸ‹Ÿú i Ø¡G¡¶¢&¢–££v£æ¤V¤Ç¥8¥©¦¦‹¦ý§n§à¨R¨Ä©7©©ªª««u«é¬\¬Ð­D­¸®-®¡¯¯‹° °u°ê±`±Ö²K²Â³8³®´%´œµµŠ¶¶y¶ð·h·à¸Y¸Ñ¹J¹Âº;ºµ».»§¼!¼›½½¾
¾„¾ÿ¿z¿õÀpÀìÁgÁãÂ_ÂÛÃXÃÔÄQÄÎÅKÅÈÆFÆÃÇAÇ¿È=È¼É:É¹Ê8Ê·Ë6Ë¶Ì5ÌµÍ5ÍµÎ6Î¶Ï7Ï¸Ð9ÐºÑ<Ñ¾Ò?ÒÁÓDÓÆÔIÔËÕNÕÑÖUÖØ×\×àØdØèÙlÙñÚvÚûÛ€ÜÜŠÝÝ–ÞÞ¢ß)ß¯à6à½áDáÌâSâÛãcãëäsäüå„ææ–çç©è2è¼éFéÐê[êåëpëûì†ííœî(î´ï@ïÌðXðåñrñÿòŒóó§ô4ôÂõPõÞömöû÷Šøø¨ù8ùÇúWúçûwüü˜ý)ýºþKþÜÿmÿÿÿî Adobe d    ÿÛ „ 		



ÿÀ  2 ÿÝ  $ÿÄ¢            	
         	
 s !1AQa"q2‘¡±B#ÁRÑá3bð$r‚ñ%C4S’¢²csÂ5D'“£³6TdtÃÒâ&ƒ	
„”EF¤´VÓU(òãóÄÔäôeu…•¥µÅÕåõfv†–¦¶ÆÖæö7GWgw‡—§·Ç×ç÷8HXhxˆ˜¨¸ÈØèø)9IYiy‰™©¹ÉÙéù*:JZjzŠšªºÊÚêú m !1AQa"q‘2¡±ðÁÑá#BRbrñ3$4C‚’S%¢c²ÂsÒ5âDƒT“	
&6E'dtU7ò£³Ã()Óãó„”¤´ÄÔäôeu…•¥µÅÕåõFVfv†–¦¶ÆÖæöGWgw‡—§·Ç×ç÷8HXhxˆ˜¨¸ÈØèø9IYiy‰™©¹ÉÙéù*:JZjzŠšªºÊÚêúÿÚ   ? õN*§ssokOq*Ã

¼ŽB¨3€9 Èeçž`üÝ†)L:qÄÑ®gÓùÇæÜs.¸£»—]üÔÓË™ÚF¨VÚü>ôì9Ü¹ÿ %ÏCþKå¸uqžÇÒ[0ë#-¤³0A ƒPzËsŠ»v*ìUØ«±Wb®Å]Š»v*ìUØ«±Wb®Å]Š»v*ìUØ«±Wb®Å]Š»v*ìUØ«±Wb¯ÿÐô<óoåÁ¹¾KÇ<QTrcóý‘˜ÚHÇïqµ‘n¯!×<Ë¬k“zº…Á‘Aª@¿Iþªtÿ d~,ÔåÍ)ó.«&YLîRÀAèk•5»c·áŠ²O-ùÿ \ÐøÄ$úÝ€ØÛLIâ<#~©òû9“‡U(y†üZ™CÌ=‹Ëšýž½¥¦¡j¬ŠÄ£Æÿ i]~Òí×ç›|YDãaÛâÊ'o[ó˜.¼ÚÞ]Ò.¡Ó„	%¹C—bQmÑ‡ü6Q“$ÎNžœl™frpDð¦Tó…å›ýC^x/.mmý P:’9mÝeÉñÎ&[Ógáe»¸óŸ´Í"ÓÌw³ÛMarÈ^ÀF–97Z0ßâå|9ŽråŒDÍWó\c—,b&H£ü)äÞfÔ[ÏZV›€iw¶ŸXhÊD”‘åÔ}•Ë¥”ø¢#é!¼æ>(é_w®k'ÏgD·™ÕìZXÃ 4š‡‹Ö€öÆY%âðôáL²KÅá¸RKGóßÌvzê–­qy•& (cB)_ØÊŒ²‰ˆñüšLó	ˆX²š_k^cÓuÏ-éwWQJ×ž Ô#\ƒ·Š®ÙdòN2ŒIçõ6K$ã(ÄžR¶¯æ-J=i:M¼«õ¨‹NœU‰aÏöº²2sÈFHÄr)ÉšC(ˆäRMYóæ»> -uK[hìçh‚Í
’G&¥(<S	å™4@á-8²eÑ#¼Ó¬ù¯FÒ´h…ì/©]Ü471°bxQHÚ€®K4çÇQ,ódÉÇQi5ß7hÞfÓtÍjâÞúÛR< N†´ ý¢12Bb2"\Kâä„À‘Q¶óýå·ž®ôJDýf0[·SmÄ³wSöwÈÇRFSô jˆÊb~”ãËÚî§{æÍ{N¸‘ZÒÅ[ P
òëR79n,’3<¢Ý‹$ŽIÊ)¯šoîtÿ /_ÞÚ°Kˆ!g‰ˆc–æ‘Œ	™¤cC1yúÏË¶ÞešòÖâÆNö†0ÅÛ* ÿ …9†reŒÉ8^6Q;šê¾h×õnÏEÐv’Ml—“ÝL¡Ê¤‹È ½6¨Ë'šRŒ6Û‰¶y§)Ãm¸—è>d×–÷WÑ5–õ->¸‚æ%¢ºq½?iyerŒ¾¨§iÜ£/ª(ÿ ËÝoQÖ|º·º„‚Kƒ,ˆYT ¢Ò›ž—!œ,³Òä3…”˜yãPÒ%×¬uÉKËõtæ
©ê£ì‚‚•;£öË•~`ÃˆKœ~–ŸÌ˜q	sJ!Oæž\¶Ô†£3ú\ÝG$+^4å­Ç€ø«ûY/Þ˜{û™^^+ùÿ Î´j×·Ð>› 5°ˆ,œ–ª )ö°i¥’cˆŸJtòÉ/Q>”·ËšŸæ½`÷°jÖ–è²´\%…yUhk°÷ÊðË,Å‰“^)å˜°Be¯ëÞg°:>…m$2ëš€>µéZDÙR™n\³G×&y2Î<1\¿‰_K¼ó½Ž£qc¬*ÞÚ˜[}R
Šê¤…p)ÖŸË† $KqüæP–X’%¸þrÏ,y—S¾òEÖ©w25üKrQÂªŠÆ	O„mŽŸ)–>#ÏtbÍ#ˆÈý[¥Z‡œüÃåþ™¬Ç:Bæá£šC•*¢œiAö+–y"_ÄÕ=DÆ!.¤þµ}cÏ·ry*×YÓ$Xoá-îÐ¨~Å¹-/ù8g¨'”yÛ,š£á‰G¦º®½©ÛùãGÒ¢‘Eä,óÆTX¥¨û#,žB2F=lòÈeŒz·ô×œõígTƒB¸·±³ÒÜÃYP;K $u!©Ë‰ÿ W+ñ2NDDˆˆµø™'""xDQŸ§¼çþõ¿D?éïWêþŸ†”¯¯Æ¿g·_k'âdà¾_ãÔÏÅÉÁË×øõ?ÿÑì~·±¸óîƒõ>©**Ê	  ÈÔR|¨¹¯Ô€rÄN»TËy%·wz\Úí¶•w¥EiªZêÑ$&•#k3 dßãä7û9(™ˆ‘Rÿ `Õ)DÈDŠŸûO0}WP°óRKimh³Ä,§†%Ž@!VWíl0å©	‚>„å¢'°ôJŸ›fÐôå¹ÒfÒâK	l’]öÞ5õZbµæò>[7üÝŽsúHôðú˜Æ7Û‡Ñ$Eµ•™óìp˜#1~ˆW1ð^<½ò¥)\°Dx£oàLb<Zþ‡ûÔûòþQFÿ ˜©Rä´?GÅÉÐÿ wñBùÒ÷ÈêÍk¯A<7¢ñ¼Dtä¦§Š²ý°+ü¼pj%ˆÊ§Í†¢XŒªWi‹§êz‡”<Ékb'ŸK.¤‰kÍÄrs` ø¢¯OÛÊqÆRÇ >ŸàiÇ	K€ú…nµæ‹gÉº—¬£–M`"{nf„q;ûÓ™„ñˆ«ddÌ'Œ@}[&ºúÉåÿ 5yX¾F:}½¢ÚO4`°YMiþ½FY”pdŒÓ\-¹?w8Èò®}ù5ÿ ÌI59´ÛkOA®J‚ç ùáÇ.<¼Cé–)ñæâM"5üšú'üÂIÿ ›%?ïãýTäþþ>ïø¤?æ…¶¡æï.ØÜÔÁsê$O¦Çb>YTD²Dj¢%’  ËÚf…ù¢ZØJ#	¹åI©ö<Ã4@ók8„3D;£¯’ÚïSÿ I2Iõ—ú¿¢^œy7*ð¾cŠ\Îqñx{ñ²:>“{ y]4×vÓ^èAµCð_ÝŸµ½vËóðÊ¯¦ÜA‰Œ8~›_§éVXüÄ†ÞíLÖ·‘ÿ ¸»¹Ø³FäR•éZòOöIŒ 1å£Ê_Jc5GéP‹ËðëÞióuƒQfª½´§ö%VøOÈý–ÿ '"1	ä˜b1qÎaùV×Ç^Öÿ Hrúò¬KqÏísBW»%£¾9_6z+â•óeþyÿ ”GUÿ ˜vÌ½G÷gÜåj»,WÊ?—š£¢iº•ä·3PJÖ¦OÜÖ½8^?ì³–& ›..,e#jšÕä~\üÂM^ú'M*æÐ@“¢’ªËû;«Ó‡ÃËÄ~’’^^#ô§¢\gÌžaó¬nºcY5´2¸+Í‚/Oøÿ ƒãœ¦>ž\gŽr˜úxP—¾xòîåÅ³¿£¸»•»-JnÊôº˜BXéu„(¢¼ûŸæ*\„ôˆ¬H§8Œ‘²‚?Ùœž¤(ôê@”àœÏ5¯øã_ÿ Ì4¿ñ™ÓúK“é>æ;ù_ÿ (M¯úÓÄÎchÿ »?îÃÎüºž@{ý?,é{ê¸#'On?`ZòÌ^zîÝ~!Š½|Ù_˜ïí Õ|³æ‹t’]Ìm2©%Tü*XÇ^ù—˜Ô£?árrÌ	BcèNl¼ñ»{ug¥Ú¼ºtVÎóêT¸š(R7¯úßÍ—GP&Hˆô×ÔÝO"#Ó_SòÏ“´MGÉ7:ÅÀ”ÞB·
ÈUk%~·lÃÁ§Œ±ñ{¸˜°FXŒ=ÔõVÿ O¢ÿ ÇãÄ¦Ã?ñpÆÜGúßñJ~òôú<Ëqiði›Fïý”iôÕ™Ù.N3céŸû¥ÕbàÜ}2ezñÿ ›åßù‡Õ&däþú>âådþú>ä¿F×ì<¥¯y‚ßYYa7w½«,$J¹§,®F)ÈK©âkÇ”b”„º”÷ük«…¿O~†~>µ>¯ê_W§÷ßc¥}¿ÊË¼ypqpÿ Ò?ÎoüÄ¸8øéÿÒêÿ š:}Þ£æ­.ÊÍyÜÍlDKPµ!Øõ=6¬Ö@Ë :ÍdL¦ çJVŽÚ½¶©Þ/[HÕ-ôë™iýòz‹Ç‘îèãoæÉCÖ##õB\,Aâ'ê„„ù’ëI±ÿ XÁz.õ-jê$6Â6AI*C»|'­6Èæ”cÄ¹Mr˜Ž Êeoe}u¡k>XÕÐ-æ‡½²”°cÉ£ä:£)øæÜŒbLe	s‡ª,DIŒ¡.põ&ÖÊßò°a$FR§Äz4¯ß™ûÑýFÈÞÿ ™þõ7ü£ÿ ”Q¿æ*_Ô¸t?GÅ¿CýßÅ1Õõé_V}#OÒ«umËrdtŠ8Ãý‘ÉÃUš•ËgñpÄYäËráã!_ô¾¿ú6	­´úÃ;$¶o<Q˜Õz0mÕ•»d¸åV"ËÄmµ	åŸ0_ë­Úèkmi!‘$¿õ£f ‚¡UÏÄ8ä0ä3ß†ƒ9LÍðÐþr¾•æÛ_\Ô´AöUâìC,Á[‹ÐSn/¶f‘óYC8œŒk’¼Õ¯Ú^ÛéƒËb+‹•w·…n¢ ¬täv^#®Dæ<<?k_0Dx9ù«êfÔmõ=>Æ=OªÝ[4æ/^51ñ$2z…hióÃ,¤HQ§šB@púˆM´›J÷œš¦”¶ÄG L±ÎX¤2ÈyŽÜfGê+5ÝV6m9šØO%íÔvŠõ ÇêWâ­J}œrO†¼Ï
å˜‰s<*:Î£c§jzU™±ŽSªLÐú”QÀªòåN'•pN@H
ú˜ä˜‰¾¢¡¦y›K½óï—ÞÙ!žÁ«o^%d ÅEZôÈÃ4e#±D3DÌÂ¾•)üÙnÚ~¹}%€èS<AY2§Ä	_ƒ”T}NqÃ#_B&ÃÌPË®A`ÖbÝï¬–ú€AçZrŒü#t¯Žå@WÕ&QËsªú£Ä…¾ó•½™×§†ÈJš?¤³L)–I>Éþî½~,Œ³Å·ÐÆZ€8ˆB"ËYó-Ü¥Ç—ÄVs•õ&7Q8ToÚ)J·ú¹(Îgœv÷²ŽIžqÛÞ…_5ë^ßÚizÖ¡Óf0;­ÄqÔ]‘—Ã#ãJÈ¾6><¬ˆÆø|×ÍçK
Òò»žþoªÃ§7Þ¸¨erßáÇíbsƒ@¾/áS¨ ÕñzxSPÕ¥’K[ýéÑÆœ‘ÒXå‰ª~ÈãÄ†ÿ c“Ç)ˆálÇ)r1áK-5›‹ýÏSÓtîMÉK–(ý1”“/ÅË†B98¢‹TrDJ1»QÓüÕ«êZoé(|º­irI†â2IˆUW‡%5SM°C4¤8¸v÷¢9å!Ä#·½7œmdÓô‰¬àúÔÚÓªAl\/JÊXÑ¶‹£m’ñÅDøÙ@¨Ð¾6CqÆ¼#Pˆ:*€Ü2úr Sú—ü³Åÿ  ¿ÓGîTôbôý.éÒœ(8Óå…4ŽbON(ÕùT >á( 9!…Æˆ«­P ývÆ–ƒFÚØÆ#1!MU8Ž û¼!t‘E"ð‘×ùX6ö8iHqŠ"ë!E2.Êä
‘Æ––Ëoo5=h’N;¯5O•p¤ÍR‚”íá…/ÿÓìÿ ™º&½&¡e®iHÏõèÆ-åFV,/í.ûÓ05xçbQþYŽV%Œ÷Îža»{s4È¿Uœ\¤iF¦e5ê rožaKS3^N³Ì×’U}y=õä÷—$4÷d•€â7ZÓ)”Œ–¹H“e4»óŸ˜®ìÆ{…h¤A²ÐJè½ä“ºZ™‘D¶K<È¢UlüÛæÉm£Ò­%3Õâá¼þ™Û‚½ñÃùá	Ži×z§åî‡£yu-o”%ÃÊóÁ¯ôIrÛ6z\F¢í4¸Ì!E¬ØèwüÓÛk§HÖcìG" éÕ9¤ŸP`É™X—˜dŒLìK‚H¯"ëúž›to&_Uº’ÞÕP‚hÒ”z»öÉiædïE–›!7½©)òæ¬šOååÎ ÇxdºôÇŒ3*ø"2¬SáÃ~ÿ ½«ø1ïH­&ºÑ#Ð/¦Ó/-M”Œš•ìÁ8J—mûÂhÅ¶rye ˜p’¯ª_×h‰0á5!_WùÌÇU#üy ÿ Ì5ßê\ÊŸ÷±÷IÌŸ÷±÷I)ójóÞ–£Q:Y6Rÿ ¦‚ŸøyðüYVaûÑ¿¤µgþôoÃédþ^P–²Gú_ôÃ‡äg&2T(Ÿ»Ûµs'.|NN_WUçùÞöZ‹kMNÞ[‰(HDcNÛåz“\' jÕ=Òo0^Zj^lòÌÇs%¼ÒÜÏé0p‘“­+Û#9’5æÃ,„²@÷âJN‰u¨ù’÷N>ž³¦ê+=Œƒö©
òˆø«ŽÙW†ddGÕzZü3)Hª2ô ì/M÷’|ãzÉé5ÄÏ#Æe™T•úOŠ?¥®2¼S>iç˜CXè^óQ—“I4¡v&	bãïã–dôÂ3þgû–ü»F3þb{­ÿ *oîn7ºÔO×gcÔ™¦Rµÿ aÇ"bFO9z˜ÖO9z¾ÔóËÑ¬7²Iæƒ|¥‹kzË@>Ž«—c^«ù7bØ_ôvH¦¾óyºïGÔÚk{·oª¢¡Ñ?•¸ýž9EOÖbz´pÎæbjŠcoeäû(hñ›æ±I¤Y]™BÌ.¨ZB\íÊ¼ƒW&#ŒãŽõüßë6ã8ã¿üR¶‰©ê6þhýúXkvOjÓÉ1Tç© ñü'Ÿ¾KˆŸñŠÿ Jœs"|<\b‘¿—?ò…Xÿ Ïoù<ù-/÷cã÷¶i?ºþ[ÿ Êaó›þO>:_îÂé?»½-ò®‰imçmsfŽÃ‡Ô¢?f/®VNöwÿ W+ÃŒ’þûÿ S^`e—ôß³ŒÌs]Š»v*ìUØ«±Wb®Å]Š¿ÿÔõN*Æ|Ëù¡ë|æáõKóZ]D ©ÿ ‹£ÿ Ä¿ÊÌ|ÚhÏÈ¸Ù´±žü‹Ê<ÁäÍ{Crn 2ÛDº†­¯J÷Sþ¶jòéç|f\‡4ÓË?–šÖªR{Ðtû¿'½q×àCÓýgË0èå-Ï¤6aÒJ[ŸHz®…åCƒÓÓíÂ1’vø¥õœïô}œÚcÅ
ÙãÃr	¦XÚ¿Ð´]AÕï¬`¹‘~ËË³áR+–8Ë˜¶Ås¸ ‚Þ†Ö(PQ#@@ölÉ lÇGÒMªÚ8Mª¿ª°p^ë^\iNU5ÁÁªÙ‡ªÙ^æÖÚê·¹‰f‚AGŠ@H­w	 Š,¥E•¡ž)Ì(fJC'É¶!O`i»Gæ£}¢éî²_YCrè8£K¹µ ¨9cŒ¹‹D±Æ\Å®°Ò´Í<:ØÚÅj$ È!ENDt¯0Æ<…&0Œy
Wšf‰¢™HœQãpH=ˆ8H´46Ÿ£i:qsag©“í˜‘PŸ™aòÆãB•á³µ‚I¤†ŽK†ç;ª€]©J±M0€!9(þ‰Òý+ˆ~©¥vÅ®£à¼dcÔ¸§ÄO¾ÝÍ‡"¹ªËei-¡³–{R¡ §°^'ja1]b®ŽžÎÒâØÚÏ
KlÀ)…Ô tNÛSTÄG’,ùv	’x4Ûh¦Œ†ŽD‰+„6ÈP€Œ0€YÚ@ó<0¤opÜçeP·NMN§& „@ä t=Ú3c´,\Áé¯G«q¥+‘ðãU[#ÂUl»OÒ4½9,-"µWûb$Uåó ß`#ÈRÇcÈRµ­¥­¬omCWŒQ¨U54Üá ƒ(ÄAÖ¶–¶,±$%xÅ
¢¦¦€{œ@ PXÄAÑÚZÅ<·Ä‰<ü}yU@gà(¼~#¦ j"µ\)v*ìUØ«±Wb®Å]Š»v*ÿ ÿÕõN*ìUÇ¦*ìUØ«±Wb®Å]Š»v*ìUØ«±Wb®Å]Š»v*ìUØ«±Wb®Å]Š»v*ìUØ«±Wb®Å]Š»v*ìUÿÙ